we fix many errors

diff --git a/lab6/Makefile b/lab6/Makefile
--- a/lab6/Makefile
+++ b/lab6/Makefile
@@ -1,4 +1,3 @@
-SHELL := /bin/bash
 SRC_PATH ?= src
 INC_PATH += include
 BUILD_PATH ?= build
@@ -9,7 +8,7 @@ SYSLIB_PATH ?= sysyruntimelibrary
 
 INC = $(addprefix -I, $(INC_PATH))
 SRC = $(shell find $(SRC_PATH)  -name "*.cpp")
-CFLAGS = -O2 -g -Wall -Werror $(INC)
+CFLAGS = -O0 -g -Wall -std=c++11 $(INC)
 FLEX ?= $(SRC_PATH)/lexer.l
 LEXER ?= $(addsuffix .cpp, $(basename $(FLEX)))
 BISON ?= $(SRC_PATH)/parser.y
@@ -23,15 +22,15 @@ TESTCASE = $(shell find $(TEST_PATH) -name "*.sy")
 TESTCASE_NUM = $(words $(TESTCASE))
 LLVM_IR = $(addsuffix _std.ll, $(basename $(TESTCASE)))
 GCC_ASM = $(addsuffix _std.s, $(basename $(TESTCASE)))
-OUTPUT_LAB3 = $(addsuffix .toks, $(basename $(TESTCASE)))
-OUTPUT_LAB4 = $(addsuffix .ast, $(basename $(TESTCASE)))
-OUTPUT_LAB5 = $(addsuffix .ll, $(basename $(TESTCASE)))
-OUTPUT_LAB6 = $(addsuffix .s, $(basename $(TESTCASE)))
+OUTPUT_LAB4 = $(addsuffix .toks, $(basename $(TESTCASE)))
+OUTPUT_LAB5 = $(addsuffix .ast, $(basename $(TESTCASE)))
+OUTPUT_LAB6 = $(addsuffix .ll, $(basename $(TESTCASE)))
+OUTPUT_LAB7 = $(addsuffix .s, $(basename $(TESTCASE)))
 OUTPUT_RES = $(addsuffix .res, $(basename $(TESTCASE)))
 OUTPUT_BIN = $(addsuffix .bin, $(basename $(TESTCASE)))
 OUTPUT_LOG = $(addsuffix .log, $(basename $(TESTCASE)))
 
-.phony:all app run gdb testlab3 testlab4 testlab5 testlab6 testir test clean clean-all clean-test clean-app llvmir gccasm
+.phony:all app run gdb testlab4 testlab5 testlab6 testlab7 test clean clean-all clean-test clean-app llvmir gccasm
 
 all:app
 
@@ -46,7 +45,7 @@ $(OBJ_PATH)/%.o:$(SRC_PATH)/%.cpp
 	@g++ $(CFLAGS) -c -o $@ $<
 
 $(BINARY):$(OBJ)
-	@g++ -O2 -g -o $@ $^
+	@g++ -O0 -g -o $@ $^
 
 app:$(LEXER) $(PARSER) $(BINARY)
 
@@ -83,71 +82,18 @@ llvmir:$(LLVM_IR)
 
 gccasm:$(GCC_ASM)
 
-testlab3:app $(OUTPUT_LAB3)
-
 testlab4:app $(OUTPUT_LAB4)
 
 testlab5:app $(OUTPUT_LAB5)
 
 testlab6:app $(OUTPUT_LAB6)
 
-.ONESHELL:
-testir:app
-	@success=0
-	@for file in $(sort $(TESTCASE))
-	do
-		IR=$${file%.*}.ll
-		LOG=$${file%.*}.log
-		BIN=$${file%.*}.bin
-		RES=$${file%.*}.res
-		IN=$${file%.*}.in
-		OUT=$${file%.*}.out
-		FILE=$${file##*/}
-		FILE=$${FILE%.*}
-		timeout 5s $(BINARY) $${file} -o $${IR} -i 2>$${LOG}
-		RETURN_VALUE=$$?
-		if [ $$RETURN_VALUE = 124 ]; then
-			echo -e "\033[1;31mFAIL:\033[0m $${FILE}\t\033[1;31mCompile Timeout\033[0m"
-			continue
-		else if [ $$RETURN_VALUE != 0 ]; then
-			echo -e "\033[1;31mFAIL:\033[0m $${FILE}\t\033[1;31mCompile Error\033[0m"
-			continue
-			fi
-		fi
-		clang -o $${BIN} $${IR} $(SYSLIB_PATH)/sylib.c >>$${LOG} 2>&1
-		if [ $$? != 0 ]; then
-			echo -e "\033[1;31mFAIL:\033[0m $${FILE}\t\033[1;31mAssemble Error\033[0m"
-		else
-			if [ -f "$${IN}" ]; then
-				timeout 2s $${BIN} <$${IN} >$${RES} 2>>$${LOG}
-			else
-				timeout 2s $${BIN} >$${RES} 2>>$${LOG}
-			fi
-			RETURN_VALUE=$$?
-			FINAL=`tail -c 1 $${RES}`
-			[ $${FINAL} ] && echo -e "\n$${RETURN_VALUE}" >> $${RES} || echo "$${RETURN_VALUE}" >> $${RES}
-			if [ "$${RETURN_VALUE}" = "124" ]; then
-				echo -e "\033[1;31mFAIL:\033[0m $${FILE}\t\033[1;31mExecute Timeout\033[0m"
-			else if [ "$${RETURN_VALUE}" = "127" ]; then
-				echo -e "\033[1;31mFAIL:\033[0m $${FILE}\t\033[1;31mExecute Error\033[0m"
-				else
-					diff -Z $${RES} $${OUT} >/dev/null 2>&1
-					if [ $$? != 0 ]; then
-						echo -e "\033[1;31mFAIL:\033[0m $${FILE}\t\033[1;31mWrong Answer\033[0m"
-					else
-						success=$$((success + 1))
-						echo -e "\033[1;32mPASS:\033[0m $${FILE}"
-					fi
-				fi
-			fi
-		fi
-	done
-	echo -e "\033[1;33mTotal: $(TESTCASE_NUM)\t\033[1;32mAccept: $${success}\t\033[1;31mFail: $$(($(TESTCASE_NUM) - $${success}))\033[0m"
-	[ $(TESTCASE_NUM) = $${success} ] && echo -e "\033[5;32mAll Accepted. Congratulations!\033[0m"
-	:
+testlab7:app $(OUTPUT_LAB7)
 
 .ONESHELL:
 test:app
+	@cp -r -f newpass.log lastpass.log
+	@rm newpass.log
 	@success=0
 	@for file in $(sort $(TESTCASE))
 	do
@@ -162,16 +108,16 @@ test:app
 		timeout 5s $(BINARY) $${file} -o $${ASM} -S 2>$${LOG}
 		RETURN_VALUE=$$?
 		if [ $$RETURN_VALUE = 124 ]; then
-			echo -e "\033[1;31mFAIL:\033[0m $${FILE}\t\033[1;31mCompile Timeout\033[0m"
+			echo "\033[1;31mFAIL:\033[0m $${FILE}\t\033[1;31mCompile Timeout\033[0m" && echo "FAIL: $${FILE}\tCompile Timeout" >> newpass.log
 			continue
 		else if [ $$RETURN_VALUE != 0 ]; then
-			echo -e "\033[1;31mFAIL:\033[0m $${FILE}\t\033[1;31mCompile Error\033[0m"
+			echo "\033[1;31mFAIL:\033[0m $${FILE}\t\033[1;31mCompile Error\033[0m" && echo "FAIL: $${FILE}\tCompile Error" >> newpass.log
 			continue
 			fi
 		fi
 		arm-linux-gnueabihf-gcc -mcpu=cortex-a72 -o $${BIN} $${ASM} $(SYSLIB_PATH)/libsysy.a >>$${LOG} 2>&1
 		if [ $$? != 0 ]; then
-			echo -e "\033[1;31mFAIL:\033[0m $${FILE}\t\033[1;31mAssemble Error\033[0m"
+			echo "\033[1;31mFAIL:\033[0m $${FILE}\t\033[1;31mAssemble Error\033[0m" && echo "FAIL: $${FILE}\tAssemble Error" >> newpass.log
 		else
 			if [ -f "$${IN}" ]; then
 				timeout 2s qemu-arm -L /usr/arm-linux-gnueabihf $${BIN} <$${IN} >$${RES} 2>>$${LOG}
@@ -180,32 +126,33 @@ test:app
 			fi
 			RETURN_VALUE=$$?
 			FINAL=`tail -c 1 $${RES}`
-			[ $${FINAL} ] && echo -e "\n$${RETURN_VALUE}" >> $${RES} || echo "$${RETURN_VALUE}" >> $${RES}
+			[ $${FINAL} ] && echo "\n$${RETURN_VALUE}" >> $${RES} || echo "$${RETURN_VALUE}" >> $${RES}
 			if [ "$${RETURN_VALUE}" = "124" ]; then
-				echo -e "\033[1;31mFAIL:\033[0m $${FILE}\t\033[1;31mExecute Timeout\033[0m"
+				echo "\033[1;31mFAIL:\033[0m $${FILE}\t\033[1;31mExecute Timeout\033[0m" && echo "FAIL: $${FILE}\tExecute Timeout" >> newpass.log
 			else if [ "$${RETURN_VALUE}" = "127" ]; then
-				echo -e "\033[1;31mFAIL:\033[0m $${FILE}\t\033[1;31mExecute Error\033[0m"
+				echo "\033[1;31mFAIL:\033[0m $${FILE}\t\033[1;31mExecute Error\033[0m" && echo "FAIL: $${FILE}\tExecute Error" >> newpass.log
 				else
 					diff -Z $${RES} $${OUT} >/dev/null 2>&1
 					if [ $$? != 0 ]; then
-						echo -e "\033[1;31mFAIL:\033[0m $${FILE}\t\033[1;31mWrong Answer\033[0m"
+						echo "\033[1;31mFAIL:\033[0m $${FILE}\t\033[1;31mWrong Answer\033[0m" && echo "FAIL: $${FILE}\tWrong Answer" >> newpass.log
 					else
 						success=$$((success + 1))
-						echo -e "\033[1;32mPASS:\033[0m $${FILE}"
+						echo "\033[1;32mPASS:\033[0m $${FILE}" && echo "PASS: $${FILE}" >> newpass.log
 					fi
 				fi
 			fi
 		fi
 	done
-	echo -e "\033[1;33mTotal: $(TESTCASE_NUM)\t\033[1;32mAccept: $${success}\t\033[1;31mFail: $$(($(TESTCASE_NUM) - $${success}))\033[0m"
-	[ $(TESTCASE_NUM) = $${success} ] && echo -e "\033[5;32mAll Accepted. Congratulations!\033[0m"
+	echo "\033[1;33mTotal: $(TESTCASE_NUM)\t\033[1;32mAccept: $${success}\t\033[1;31mFail: $$(($(TESTCASE_NUM) - $${success}))\033[0m" && echo "Total: $(TESTCASE_NUM)\tAccept: $${success}\tFail: $$(($(TESTCASE_NUM) - $${success}))" >> newpass.log
+	[ $(TESTCASE_NUM) = $${success} ] && echo "\033[5;32mAll Accepted. Congratulations!\033[0m" && echo "All Accepted. Congratulations!" >> newpass.log
 	:
+	diff lastpass.log newpass.log > passchange.log
 
 clean-app:
 	@rm -rf $(BUILD_PATH) $(PARSER) $(LEXER) $(PARSERH)
 
 clean-test:
-	@rm -rf $(OUTPUT_LAB3) $(OUTPUT_LAB4) $(OUTPUT_LAB5) $(OUTPUT_LAB6) $(OUTPUT_LOG) $(OUTPUT_BIN) $(OUTPUT_RES) $(LLVM_IR) $(GCC_ASM) *.toks *.ast *.ll *.s *.out
+	@rm -rf $(OUTPUT_LAB4) $(OUTPUT_LAB5) $(OUTPUT_LAB6) $(OUTPUT_LAB7) $(OUTPUT_LOG) $(OUTPUT_BIN) $(OUTPUT_RES) $(LLVM_IR) $(GCC_ASM) ./example.ast ./example.ll ./example.s
 
 clean-all:clean-test clean-app
 
